"""Added type column in grocery_item

Revision ID: 48ce1f7224a8
Revises: fce3bd56ff78
Create Date: 2025-01-26 22:40:27.379112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ce1f7224a8'
down_revision = 'fce3bd56ff78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_item', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
