"""Add budget and dietary fields to User model

Revision ID: 5604e442fb48
Revises: 
Create Date: 2025-01-13 23:13:43.566830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5604e442fb48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('dietary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dietary')
        batch_op.drop_column('budget')

    op.create_table('user_profile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('budget', sa.FLOAT(), nullable=False),
    sa.Column('dietary_restrictions', sa.VARCHAR(length=255), nullable=False),
    sa.Column('nutrition_concerns', sa.VARCHAR(length=255), nullable=True),
    sa.Column('preferences', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
